#############################################################################
# Makefile for building: Rhino
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  Rhino.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile Rhino.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQWT_DLL -DQWT_NO_SVG -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/qwt-6.1.5/include -I. -I../../Programs/root/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Rhino1.0.0
DISTDIR = /home/gcucciat/Documents/Rhino/.tmp/Rhino1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/local/qwt-6.1.5/lib -lqwt -L/home/gcucciat/Programs/root/lib -lGui -lCore -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		mylabel.cpp \
		spectrum.cpp qrc_rhino_icon.cpp \
		moc_mainwindow.cpp \
		moc_mylabel.cpp
OBJECTS       = main.o \
		mainwindow.o \
		mylabel.o \
		spectrum.o \
		qrc_rhino_icon.o \
		moc_mainwindow.o \
		moc_mylabel.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/local/qwt-6.1.5/features/qwtconfig.pri \
		/usr/local/qwt-6.1.5/features/qwtfunctions.pri \
		/usr/local/qwt-6.1.5/features/qwt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Rhino.pro mainwindow.h \
		mylabel.h \
		spectrum.h \
		ui_mainwindow.h main.cpp \
		mainwindow.cpp \
		mylabel.cpp \
		spectrum.cpp
QMAKE_TARGET  = Rhino
DESTDIR       = 
TARGET        = Rhino


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Rhino.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/local/qwt-6.1.5/features/qwtconfig.pri \
		/usr/local/qwt-6.1.5/features/qwtfunctions.pri \
		/usr/local/qwt-6.1.5/features/qwt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Rhino.pro \
		rhino_icon.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5PrintSupport.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile Rhino.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/local/qwt-6.1.5/features/qwtconfig.pri:
/usr/local/qwt-6.1.5/features/qwtfunctions.pri:
/usr/local/qwt-6.1.5/features/qwt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Rhino.pro:
rhino_icon.qrc:
/usr/lib/x86_64-linux-gnu/libQt5PrintSupport.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Rhino.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents rhino_icon.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h mylabel.h spectrum.h ui_mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp mylabel.cpp spectrum.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_rhino_icon.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_rhino_icon.cpp
qrc_rhino_icon.cpp: rhino_icon.qrc \
		/usr/lib/qt5/bin/rcc \
		Rhino.png
	/usr/lib/qt5/bin/rcc -name rhino_icon rhino_icon.qrc -o qrc_rhino_icon.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_mylabel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_mylabel.cpp
moc_mainwindow.cpp: spectrum.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.5/include/qwt_global.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_item.h \
		/usr/local/qwt-6.1.5/include/qwt_text.h \
		/usr/local/qwt-6.1.5/include/qwt_legend_data.h \
		/usr/local/qwt-6.1.5/include/qwt_graphic.h \
		/usr/local/qwt-6.1.5/include/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.5/include/qwt_scale_div.h \
		/usr/local/qwt-6.1.5/include/qwt_interval.h \
		/usr/local/qwt-6.1.5/include/qwt_series_data.h \
		/usr/local/qwt-6.1.5/include/qwt_samples.h \
		/usr/local/qwt-6.1.5/include/qwt_point_3d.h \
		/usr/local/qwt-6.1.5/include/qwt_point_polar.h \
		/usr/local/qwt-6.1.5/include/qwt_math.h \
		/usr/local/qwt-6.1.5/include/qwt_series_store.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_picker.h \
		/usr/local/qwt-6.1.5/include/qwt_picker.h \
		/usr/local/qwt-6.1.5/include/qwt_event_pattern.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_marker.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_canvas.h \
		../../Programs/root/include/TH1F.h \
		../../Programs/root/include/TH1.h \
		../../Programs/root/include/TAxis.h \
		../../Programs/root/include/TNamed.h \
		../../Programs/root/include/TObject.h \
		../../Programs/root/include/RConfigure.h \
		../../Programs/root/include/Rtypes.h \
		../../Programs/root/include/RtypesCore.h \
		../../Programs/root/include/ROOT/RConfig.hxx \
		../../Programs/root/include/RVersion.h \
		../../Programs/root/include/DllImport.h \
		../../Programs/root/include/snprintf.h \
		../../Programs/root/include/strlcpy.h \
		../../Programs/root/include/TGenericClassInfo.h \
		../../Programs/root/include/TSchemaHelper.h \
		../../Programs/root/include/TIsAProxy.h \
		../../Programs/root/include/TVirtualIsAProxy.h \
		../../Programs/root/include/TStorage.h \
		../../Programs/root/include/TVersionCheck.h \
		../../Programs/root/include/TString.h \
		../../Programs/root/include/TMathBase.h \
		../../Programs/root/include/ROOT/RStringView.hxx \
		../../Programs/root/include/ROOT/RWrap_libcpp_string_view.h \
		../../Programs/root/include/ROOT/libcpp_string_view.h \
		../../Programs/root/include/ROOT/TypeTraits.hxx \
		../../Programs/root/include/TAttAxis.h \
		../../Programs/root/include/TArrayD.h \
		../../Programs/root/include/TArray.h \
		../../Programs/root/include/TAttLine.h \
		../../Programs/root/include/TAttFill.h \
		../../Programs/root/include/TAttMarker.h \
		../../Programs/root/include/TArrayC.h \
		../../Programs/root/include/TArrayS.h \
		../../Programs/root/include/TArrayI.h \
		../../Programs/root/include/TArrayF.h \
		../../Programs/root/include/Foption.h \
		../../Programs/root/include/Fit/FitExecutionPolicy.h \
		../../Programs/root/include/TVectorFfwd.h \
		../../Programs/root/include/TVectorDfwd.h \
		../../Programs/root/include/TFitResultPtr.h \
		../../Programs/root/include/TF1.h \
		../../Programs/root/include/TFormula.h \
		../../Programs/root/include/TBits.h \
		../../Programs/root/include/TMethodCall.h \
		../../Programs/root/include/TDictionary.h \
		../../Programs/root/include/ESTLType.h \
		../../Programs/root/include/TInterpreter.h \
		../../Programs/root/include/TDataType.h \
		../../Programs/root/include/TInterpreterValue.h \
		../../Programs/root/include/TVirtualRWMutex.h \
		../../Programs/root/include/TVirtualMutex.h \
		../../Programs/root/include/Math/Types.h \
		../../Programs/root/include/Vc/Vc \
		../../Programs/root/include/Vc/vector.h \
		../../Programs/root/include/Vc/scalar/vector.h \
		../../Programs/root/include/Vc/scalar/types.h \
		../../Programs/root/include/Vc/common/types.h \
		../../Programs/root/include/Vc/global.h \
		../../Programs/root/include/Vc/fwddecl.h \
		../../Programs/root/include/Vc/version.h \
		../../Programs/root/include/Vc/traits/type_traits.h \
		../../Programs/root/include/Vc/traits/decay.h \
		../../Programs/root/include/Vc/traits/has_no_allocated_data.h \
		../../Programs/root/include/Vc/array \
		../../Programs/root/include/Vc/common/subscript.h \
		../../Programs/root/include/Vc/vector \
		../../Programs/root/include/Vc/scalar/macros.h \
		../../Programs/root/include/Vc/common/macros.h \
		../../Programs/root/include/Vc/traits/has_contiguous_storage.h \
		../../Programs/root/include/Vc/traits/is_functor_argument_immutable.h \
		../../Programs/root/include/Vc/traits/is_output_iterator.h \
		../../Programs/root/include/Vc/traits/is_index_sequence.h \
		../../Programs/root/include/Vc/common/indexsequence.h \
		../../Programs/root/include/Vc/traits/is_implicit_cast_allowed.h \
		../../Programs/root/include/Vc/traits/has_subscript_operator.h \
		../../Programs/root/include/Vc/traits/has_multiply_operator.h \
		../../Programs/root/include/Vc/traits/has_addition_operator.h \
		../../Programs/root/include/Vc/traits/has_equality_operator.h \
		../../Programs/root/include/Vc/traits/entry_type_of.h \
		../../Programs/root/include/Vc/common/permutation.h \
		../../Programs/root/include/Vc/scalar/mask.h \
		../../Programs/root/include/Vc/common/memoryfwd.h \
		../../Programs/root/include/Vc/common/vectorabi.h \
		../../Programs/root/include/Vc/common/simdarrayfwd.h \
		../../Programs/root/include/Vc/sse/types.h \
		../../Programs/root/include/Vc/avx/types.h \
		../../Programs/root/include/Vc/common/utility.h \
		../../Programs/root/include/Vc/scalar/detail.h \
		../../Programs/root/include/Vc/common/detail.h \
		../../Programs/root/include/Vc/common/generalinterface.h \
		../../Programs/root/include/Vc/common/loadinterface.h \
		../../Programs/root/include/Vc/common/storeinterface.h \
		../../Programs/root/include/Vc/common/gatherinterface.h \
		../../Programs/root/include/Vc/common/gatherinterface_deprecated.h \
		../../Programs/root/include/Vc/common/scatterinterface.h \
		../../Programs/root/include/Vc/common/scatterinterface_deprecated.h \
		../../Programs/root/include/Vc/scalar/vector.tcc \
		../../Programs/root/include/Vc/common/data.h \
		../../Programs/root/include/Vc/common/where.h \
		../../Programs/root/include/Vc/common/transpose.h \
		../../Programs/root/include/Vc/scalar/operators.h \
		../../Programs/root/include/Vc/scalar/simd_cast.h \
		../../Programs/root/include/Vc/common/simd_cast.h \
		../../Programs/root/include/Vc/scalar/type_traits.h \
		../../Programs/root/include/Vc/sse/vector.h \
		../../Programs/root/include/Vc/sse/intrinsics.h \
		../../Programs/root/include/Vc/common/storage.h \
		../../Programs/root/include/Vc/common/aliasingentryhelper.h \
		../../Programs/root/include/Vc/common/maskbool.h \
		../../Programs/root/include/Vc/avx/intrinsics.h \
		../../Programs/root/include/Vc/common/fix_clang_emmintrin.h \
		../../Programs/root/include/Vc/sse/const_data.h \
		../../Programs/root/include/Vc/sse/debug.h \
		../../Programs/root/include/Vc/sse/shuffle.h \
		../../Programs/root/include/Vc/sse/vectorhelper.h \
		../../Programs/root/include/Vc/common/loadstoreflags.h \
		../../Programs/root/include/Vc/sse/vectorhelper.tcc \
		../../Programs/root/include/Vc/common/writemaskedvector.h \
		../../Programs/root/include/Vc/avx/vector.h \
		../../Programs/root/include/Vc/avx/casts.h \
		../../Programs/root/include/Vc/sse/casts.h \
		../../Programs/root/include/Vc/common/operators.h \
		../../Programs/root/include/Vc/common/simdarray.h \
		../../Programs/root/include/Vc/common/simdarrayhelper.h \
		../../Programs/root/include/Vc/common/simdmaskarray.h \
		../../Programs/root/include/Vc/common/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/common/interleave.h \
		../../Programs/root/include/Vc/common/alignedbase.h \
		../../Programs/root/include/Vc/scalar/helperimpl.h \
		../../Programs/root/include/Vc/scalar/math.h \
		../../Programs/root/include/Vc/scalar/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/sse/helperimpl.h \
		../../Programs/root/include/Vc/sse/deinterleave.tcc \
		../../Programs/root/include/Vc/sse/prefetches.tcc \
		../../Programs/root/include/Vc/sse/math.h \
		../../Programs/root/include/Vc/sse/const.h \
		../../Programs/root/include/Vc/sse/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/avx/helperimpl.h \
		../../Programs/root/include/Vc/avx/math.h \
		../../Programs/root/include/Vc/avx/limits.h \
		../../Programs/root/include/Vc/avx/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/common/math.h \
		../../Programs/root/include/Vc/common/trigonometric.h \
		../../Programs/root/include/Vc/common/logarithm.h \
		../../Programs/root/include/Vc/common/exponential.h \
		../../Programs/root/include/Vc/common/vectortuple.h \
		../../Programs/root/include/Vc/common/iif.h \
		../../Programs/root/include/Vc/type_traits \
		../../Programs/root/include/Vc/IO \
		../../Programs/root/include/Vc/Memory \
		../../Programs/root/include/Vc/common/memory.h \
		../../Programs/root/include/Vc/common/memorybase.h \
		../../Programs/root/include/Vc/common/malloc.h \
		../../Programs/root/include/Vc/common/interleavedmemory.h \
		../../Programs/root/include/Vc/common/make_unique.h \
		../../Programs/root/include/Vc/Utils \
		../../Programs/root/include/Vc/common/deinterleave.h \
		../../Programs/root/include/Vc/common/makeContainer.h \
		../../Programs/root/include/Vc/Allocator \
		../../Programs/root/include/Vc/iterators \
		../../Programs/root/include/Vc/common/iterators.h \
		../../Programs/root/include/Vc/common/elementreference.h \
		../../Programs/root/include/Vc/simdize \
		../../Programs/root/include/Vc/common/simdize.h \
		../../Programs/root/include/Vc/span \
		../../Programs/root/include/Vc/common/span.h \
		../../Programs/root/include/VecCore/VecCore \
		../../Programs/root/include/VecCore/Version.h \
		../../Programs/root/include/VecCore/Assert.h \
		../../Programs/root/include/VecCore/Common.h \
		../../Programs/root/include/VecCore/CUDA.h \
		../../Programs/root/include/VecCore/SIMD.h \
		../../Programs/root/include/VecCore/Types.h \
		../../Programs/root/include/VecCore/Backend/Interface.h \
		../../Programs/root/include/VecCore/Backend/Implementation.h \
		../../Programs/root/include/VecCore/Limits.h \
		../../Programs/root/include/VecCore/Backend/Deprecated.h \
		../../Programs/root/include/VecCore/Backend/Scalar.h \
		../../Programs/root/include/VecCore/Backend/ScalarWrapper.h \
		../../Programs/root/include/VecCore/Backend/SIMDSizes.h \
		../../Programs/root/include/VecCore/Backend/Vc.h \
		../../Programs/root/include/VecCore/Backend/VcScalar.h \
		../../Programs/root/include/VecCore/Backend/VcVector.h \
		../../Programs/root/include/VecCore/Backend/VcSimdArray.h \
		../../Programs/root/include/VecCore/Backend/UMESimd.h \
		../../Programs/root/include/VecCore/Backend/UMESimdCommon.h \
		../../Programs/root/include/VecCore/Backend/UMESimdArray.h \
		../../Programs/root/include/VecCore/VecMath.h \
		../../Programs/root/include/VecCore/Utilities.h \
		../../Programs/root/include/TF1AbsComposition.h \
		../../Programs/root/include/TMath.h \
		../../Programs/root/include/TError.h \
		../../Programs/root/include/Math/ParamFunctor.h \
		../../Programs/root/include/TGraph.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_histogram.h \
		/usr/local/qwt-6.1.5/include/qwt_column_symbol.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_curve.h \
		/usr/local/qwt-6.1.5/include/qwt_picker_machine.h \
		mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gcucciat/Documents/Rhino -I/usr/local/qwt-6.1.5/include -I/home/gcucciat/Documents/Rhino -I/home/gcucciat/Programs/root/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_mylabel.cpp: mylabel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/gcucciat/Documents/Rhino -I/usr/local/qwt-6.1.5/include -I/home/gcucciat/Documents/Rhino -I/home/gcucciat/Programs/root/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mylabel.h -o moc_mylabel.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic \
		/usr/local/qwt-6.1.5/include/qwt_plot.h \
		/usr/local/qwt-6.1.5/include/qwt_global.h \
		/usr/local/qwt-6.1.5/include/qwt_text.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_dict.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_item.h \
		/usr/local/qwt-6.1.5/include/qwt_legend_data.h \
		/usr/local/qwt-6.1.5/include/qwt_graphic.h \
		/usr/local/qwt-6.1.5/include/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.5/include/qwt_scale_map.h \
		/usr/local/qwt-6.1.5/include/qwt_transform.h \
		/usr/local/qwt-6.1.5/include/qwt_interval.h
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ../../Programs/root/include/TApplication.h \
		../../Programs/root/include/TObject.h \
		../../Programs/root/include/RConfigure.h \
		../../Programs/root/include/Rtypes.h \
		../../Programs/root/include/RtypesCore.h \
		../../Programs/root/include/ROOT/RConfig.hxx \
		../../Programs/root/include/RVersion.h \
		../../Programs/root/include/DllImport.h \
		../../Programs/root/include/snprintf.h \
		../../Programs/root/include/strlcpy.h \
		../../Programs/root/include/TGenericClassInfo.h \
		../../Programs/root/include/TSchemaHelper.h \
		../../Programs/root/include/TIsAProxy.h \
		../../Programs/root/include/TVirtualIsAProxy.h \
		../../Programs/root/include/TStorage.h \
		../../Programs/root/include/TVersionCheck.h \
		../../Programs/root/include/TQObject.h \
		../../Programs/root/include/TList.h \
		../../Programs/root/include/TSeqCollection.h \
		../../Programs/root/include/TCollection.h \
		../../Programs/root/include/TIterator.h \
		../../Programs/root/include/TString.h \
		../../Programs/root/include/TMathBase.h \
		../../Programs/root/include/ROOT/RStringView.hxx \
		../../Programs/root/include/ROOT/RWrap_libcpp_string_view.h \
		../../Programs/root/include/ROOT/libcpp_string_view.h \
		../../Programs/root/include/ROOT/TypeTraits.hxx \
		../../Programs/root/include/TVirtualRWMutex.h \
		../../Programs/root/include/TVirtualMutex.h \
		../../Programs/root/include/TVirtualQConnection.h \
		../../Programs/root/include/TInterpreter.h \
		../../Programs/root/include/TDataType.h \
		../../Programs/root/include/TDictionary.h \
		../../Programs/root/include/TNamed.h \
		../../Programs/root/include/ESTLType.h \
		../../Programs/root/include/TInterpreterValue.h \
		../../Programs/root/include/TQClass.h \
		../../Programs/root/include/TClass.h \
		../../Programs/root/include/TObjArray.h \
		../../Programs/root/include/TApplicationImp.h \
		mainwindow.h \
		spectrum.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.5/include/qwt_global.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_item.h \
		/usr/local/qwt-6.1.5/include/qwt_text.h \
		/usr/local/qwt-6.1.5/include/qwt_legend_data.h \
		/usr/local/qwt-6.1.5/include/qwt_graphic.h \
		/usr/local/qwt-6.1.5/include/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.5/include/qwt_scale_div.h \
		/usr/local/qwt-6.1.5/include/qwt_interval.h \
		/usr/local/qwt-6.1.5/include/qwt_series_data.h \
		/usr/local/qwt-6.1.5/include/qwt_samples.h \
		/usr/local/qwt-6.1.5/include/qwt_point_3d.h \
		/usr/local/qwt-6.1.5/include/qwt_point_polar.h \
		/usr/local/qwt-6.1.5/include/qwt_math.h \
		/usr/local/qwt-6.1.5/include/qwt_series_store.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_picker.h \
		/usr/local/qwt-6.1.5/include/qwt_picker.h \
		/usr/local/qwt-6.1.5/include/qwt_event_pattern.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_marker.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_canvas.h \
		../../Programs/root/include/TH1F.h \
		../../Programs/root/include/TH1.h \
		../../Programs/root/include/TAxis.h \
		../../Programs/root/include/TAttAxis.h \
		../../Programs/root/include/TArrayD.h \
		../../Programs/root/include/TArray.h \
		../../Programs/root/include/TAttLine.h \
		../../Programs/root/include/TAttFill.h \
		../../Programs/root/include/TAttMarker.h \
		../../Programs/root/include/TArrayC.h \
		../../Programs/root/include/TArrayS.h \
		../../Programs/root/include/TArrayI.h \
		../../Programs/root/include/TArrayF.h \
		../../Programs/root/include/Foption.h \
		../../Programs/root/include/Fit/FitExecutionPolicy.h \
		../../Programs/root/include/TVectorFfwd.h \
		../../Programs/root/include/TVectorDfwd.h \
		../../Programs/root/include/TFitResultPtr.h \
		../../Programs/root/include/TF1.h \
		../../Programs/root/include/TFormula.h \
		../../Programs/root/include/TBits.h \
		../../Programs/root/include/TMethodCall.h \
		../../Programs/root/include/Math/Types.h \
		../../Programs/root/include/Vc/Vc \
		../../Programs/root/include/Vc/vector.h \
		../../Programs/root/include/Vc/scalar/vector.h \
		../../Programs/root/include/Vc/scalar/types.h \
		../../Programs/root/include/Vc/common/types.h \
		../../Programs/root/include/Vc/global.h \
		../../Programs/root/include/Vc/fwddecl.h \
		../../Programs/root/include/Vc/version.h \
		../../Programs/root/include/Vc/traits/type_traits.h \
		../../Programs/root/include/Vc/traits/decay.h \
		../../Programs/root/include/Vc/traits/has_no_allocated_data.h \
		../../Programs/root/include/Vc/array \
		../../Programs/root/include/Vc/common/subscript.h \
		../../Programs/root/include/Vc/vector \
		../../Programs/root/include/Vc/scalar/macros.h \
		../../Programs/root/include/Vc/common/macros.h \
		../../Programs/root/include/Vc/traits/has_contiguous_storage.h \
		../../Programs/root/include/Vc/traits/is_functor_argument_immutable.h \
		../../Programs/root/include/Vc/traits/is_output_iterator.h \
		../../Programs/root/include/Vc/traits/is_index_sequence.h \
		../../Programs/root/include/Vc/common/indexsequence.h \
		../../Programs/root/include/Vc/traits/is_implicit_cast_allowed.h \
		../../Programs/root/include/Vc/traits/has_subscript_operator.h \
		../../Programs/root/include/Vc/traits/has_multiply_operator.h \
		../../Programs/root/include/Vc/traits/has_addition_operator.h \
		../../Programs/root/include/Vc/traits/has_equality_operator.h \
		../../Programs/root/include/Vc/traits/entry_type_of.h \
		../../Programs/root/include/Vc/common/permutation.h \
		../../Programs/root/include/Vc/scalar/mask.h \
		../../Programs/root/include/Vc/common/memoryfwd.h \
		../../Programs/root/include/Vc/common/vectorabi.h \
		../../Programs/root/include/Vc/common/simdarrayfwd.h \
		../../Programs/root/include/Vc/sse/types.h \
		../../Programs/root/include/Vc/avx/types.h \
		../../Programs/root/include/Vc/common/utility.h \
		../../Programs/root/include/Vc/scalar/detail.h \
		../../Programs/root/include/Vc/common/detail.h \
		../../Programs/root/include/Vc/common/generalinterface.h \
		../../Programs/root/include/Vc/common/loadinterface.h \
		../../Programs/root/include/Vc/common/storeinterface.h \
		../../Programs/root/include/Vc/common/gatherinterface.h \
		../../Programs/root/include/Vc/common/gatherinterface_deprecated.h \
		../../Programs/root/include/Vc/common/scatterinterface.h \
		../../Programs/root/include/Vc/common/scatterinterface_deprecated.h \
		../../Programs/root/include/Vc/scalar/vector.tcc \
		../../Programs/root/include/Vc/common/data.h \
		../../Programs/root/include/Vc/common/where.h \
		../../Programs/root/include/Vc/common/transpose.h \
		../../Programs/root/include/Vc/scalar/operators.h \
		../../Programs/root/include/Vc/scalar/simd_cast.h \
		../../Programs/root/include/Vc/common/simd_cast.h \
		../../Programs/root/include/Vc/scalar/type_traits.h \
		../../Programs/root/include/Vc/sse/vector.h \
		../../Programs/root/include/Vc/sse/intrinsics.h \
		../../Programs/root/include/Vc/common/storage.h \
		../../Programs/root/include/Vc/common/aliasingentryhelper.h \
		../../Programs/root/include/Vc/common/maskbool.h \
		../../Programs/root/include/Vc/avx/intrinsics.h \
		../../Programs/root/include/Vc/common/fix_clang_emmintrin.h \
		../../Programs/root/include/Vc/sse/const_data.h \
		../../Programs/root/include/Vc/sse/debug.h \
		../../Programs/root/include/Vc/sse/shuffle.h \
		../../Programs/root/include/Vc/sse/vectorhelper.h \
		../../Programs/root/include/Vc/common/loadstoreflags.h \
		../../Programs/root/include/Vc/sse/vectorhelper.tcc \
		../../Programs/root/include/Vc/common/writemaskedvector.h \
		../../Programs/root/include/Vc/avx/vector.h \
		../../Programs/root/include/Vc/avx/casts.h \
		../../Programs/root/include/Vc/sse/casts.h \
		../../Programs/root/include/Vc/common/operators.h \
		../../Programs/root/include/Vc/common/simdarray.h \
		../../Programs/root/include/Vc/common/simdarrayhelper.h \
		../../Programs/root/include/Vc/common/simdmaskarray.h \
		../../Programs/root/include/Vc/common/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/common/interleave.h \
		../../Programs/root/include/Vc/common/alignedbase.h \
		../../Programs/root/include/Vc/scalar/helperimpl.h \
		../../Programs/root/include/Vc/scalar/math.h \
		../../Programs/root/include/Vc/scalar/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/sse/helperimpl.h \
		../../Programs/root/include/Vc/sse/deinterleave.tcc \
		../../Programs/root/include/Vc/sse/prefetches.tcc \
		../../Programs/root/include/Vc/sse/math.h \
		../../Programs/root/include/Vc/sse/const.h \
		../../Programs/root/include/Vc/sse/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/avx/helperimpl.h \
		../../Programs/root/include/Vc/avx/math.h \
		../../Programs/root/include/Vc/avx/limits.h \
		../../Programs/root/include/Vc/avx/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/common/math.h \
		../../Programs/root/include/Vc/common/trigonometric.h \
		../../Programs/root/include/Vc/common/logarithm.h \
		../../Programs/root/include/Vc/common/exponential.h \
		../../Programs/root/include/Vc/common/vectortuple.h \
		../../Programs/root/include/Vc/common/iif.h \
		../../Programs/root/include/Vc/type_traits \
		../../Programs/root/include/Vc/IO \
		../../Programs/root/include/Vc/Memory \
		../../Programs/root/include/Vc/common/memory.h \
		../../Programs/root/include/Vc/common/memorybase.h \
		../../Programs/root/include/Vc/common/malloc.h \
		../../Programs/root/include/Vc/common/interleavedmemory.h \
		../../Programs/root/include/Vc/common/make_unique.h \
		../../Programs/root/include/Vc/Utils \
		../../Programs/root/include/Vc/common/deinterleave.h \
		../../Programs/root/include/Vc/common/makeContainer.h \
		../../Programs/root/include/Vc/Allocator \
		../../Programs/root/include/Vc/iterators \
		../../Programs/root/include/Vc/common/iterators.h \
		../../Programs/root/include/Vc/common/elementreference.h \
		../../Programs/root/include/Vc/simdize \
		../../Programs/root/include/Vc/common/simdize.h \
		../../Programs/root/include/Vc/span \
		../../Programs/root/include/Vc/common/span.h \
		../../Programs/root/include/VecCore/VecCore \
		../../Programs/root/include/VecCore/Version.h \
		../../Programs/root/include/VecCore/Assert.h \
		../../Programs/root/include/VecCore/Common.h \
		../../Programs/root/include/VecCore/CUDA.h \
		../../Programs/root/include/VecCore/SIMD.h \
		../../Programs/root/include/VecCore/Types.h \
		../../Programs/root/include/VecCore/Backend/Interface.h \
		../../Programs/root/include/VecCore/Backend/Implementation.h \
		../../Programs/root/include/VecCore/Limits.h \
		../../Programs/root/include/VecCore/Backend/Deprecated.h \
		../../Programs/root/include/VecCore/Backend/Scalar.h \
		../../Programs/root/include/VecCore/Backend/ScalarWrapper.h \
		../../Programs/root/include/VecCore/Backend/SIMDSizes.h \
		../../Programs/root/include/VecCore/Backend/Vc.h \
		../../Programs/root/include/VecCore/Backend/VcScalar.h \
		../../Programs/root/include/VecCore/Backend/VcVector.h \
		../../Programs/root/include/VecCore/Backend/VcSimdArray.h \
		../../Programs/root/include/VecCore/Backend/UMESimd.h \
		../../Programs/root/include/VecCore/Backend/UMESimdCommon.h \
		../../Programs/root/include/VecCore/Backend/UMESimdArray.h \
		../../Programs/root/include/VecCore/VecMath.h \
		../../Programs/root/include/VecCore/Utilities.h \
		../../Programs/root/include/TF1AbsComposition.h \
		../../Programs/root/include/TMath.h \
		../../Programs/root/include/TError.h \
		../../Programs/root/include/Math/ParamFunctor.h \
		../../Programs/root/include/TGraph.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_histogram.h \
		/usr/local/qwt-6.1.5/include/qwt_column_symbol.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_curve.h \
		/usr/local/qwt-6.1.5/include/qwt_picker_machine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		spectrum.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.5/include/qwt_global.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_item.h \
		/usr/local/qwt-6.1.5/include/qwt_text.h \
		/usr/local/qwt-6.1.5/include/qwt_legend_data.h \
		/usr/local/qwt-6.1.5/include/qwt_graphic.h \
		/usr/local/qwt-6.1.5/include/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.5/include/qwt_scale_div.h \
		/usr/local/qwt-6.1.5/include/qwt_interval.h \
		/usr/local/qwt-6.1.5/include/qwt_series_data.h \
		/usr/local/qwt-6.1.5/include/qwt_samples.h \
		/usr/local/qwt-6.1.5/include/qwt_point_3d.h \
		/usr/local/qwt-6.1.5/include/qwt_point_polar.h \
		/usr/local/qwt-6.1.5/include/qwt_math.h \
		/usr/local/qwt-6.1.5/include/qwt_series_store.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_picker.h \
		/usr/local/qwt-6.1.5/include/qwt_picker.h \
		/usr/local/qwt-6.1.5/include/qwt_event_pattern.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_marker.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_canvas.h \
		../../Programs/root/include/TH1F.h \
		../../Programs/root/include/TH1.h \
		../../Programs/root/include/TAxis.h \
		../../Programs/root/include/TNamed.h \
		../../Programs/root/include/TObject.h \
		../../Programs/root/include/RConfigure.h \
		../../Programs/root/include/Rtypes.h \
		../../Programs/root/include/RtypesCore.h \
		../../Programs/root/include/ROOT/RConfig.hxx \
		../../Programs/root/include/RVersion.h \
		../../Programs/root/include/DllImport.h \
		../../Programs/root/include/snprintf.h \
		../../Programs/root/include/strlcpy.h \
		../../Programs/root/include/TGenericClassInfo.h \
		../../Programs/root/include/TSchemaHelper.h \
		../../Programs/root/include/TIsAProxy.h \
		../../Programs/root/include/TVirtualIsAProxy.h \
		../../Programs/root/include/TStorage.h \
		../../Programs/root/include/TVersionCheck.h \
		../../Programs/root/include/TString.h \
		../../Programs/root/include/TMathBase.h \
		../../Programs/root/include/ROOT/RStringView.hxx \
		../../Programs/root/include/ROOT/RWrap_libcpp_string_view.h \
		../../Programs/root/include/ROOT/libcpp_string_view.h \
		../../Programs/root/include/ROOT/TypeTraits.hxx \
		../../Programs/root/include/TAttAxis.h \
		../../Programs/root/include/TArrayD.h \
		../../Programs/root/include/TArray.h \
		../../Programs/root/include/TAttLine.h \
		../../Programs/root/include/TAttFill.h \
		../../Programs/root/include/TAttMarker.h \
		../../Programs/root/include/TArrayC.h \
		../../Programs/root/include/TArrayS.h \
		../../Programs/root/include/TArrayI.h \
		../../Programs/root/include/TArrayF.h \
		../../Programs/root/include/Foption.h \
		../../Programs/root/include/Fit/FitExecutionPolicy.h \
		../../Programs/root/include/TVectorFfwd.h \
		../../Programs/root/include/TVectorDfwd.h \
		../../Programs/root/include/TFitResultPtr.h \
		../../Programs/root/include/TF1.h \
		../../Programs/root/include/TFormula.h \
		../../Programs/root/include/TBits.h \
		../../Programs/root/include/TMethodCall.h \
		../../Programs/root/include/TDictionary.h \
		../../Programs/root/include/ESTLType.h \
		../../Programs/root/include/TInterpreter.h \
		../../Programs/root/include/TDataType.h \
		../../Programs/root/include/TInterpreterValue.h \
		../../Programs/root/include/TVirtualRWMutex.h \
		../../Programs/root/include/TVirtualMutex.h \
		../../Programs/root/include/Math/Types.h \
		../../Programs/root/include/Vc/Vc \
		../../Programs/root/include/Vc/vector.h \
		../../Programs/root/include/Vc/scalar/vector.h \
		../../Programs/root/include/Vc/scalar/types.h \
		../../Programs/root/include/Vc/common/types.h \
		../../Programs/root/include/Vc/global.h \
		../../Programs/root/include/Vc/fwddecl.h \
		../../Programs/root/include/Vc/version.h \
		../../Programs/root/include/Vc/traits/type_traits.h \
		../../Programs/root/include/Vc/traits/decay.h \
		../../Programs/root/include/Vc/traits/has_no_allocated_data.h \
		../../Programs/root/include/Vc/array \
		../../Programs/root/include/Vc/common/subscript.h \
		../../Programs/root/include/Vc/vector \
		../../Programs/root/include/Vc/scalar/macros.h \
		../../Programs/root/include/Vc/common/macros.h \
		../../Programs/root/include/Vc/traits/has_contiguous_storage.h \
		../../Programs/root/include/Vc/traits/is_functor_argument_immutable.h \
		../../Programs/root/include/Vc/traits/is_output_iterator.h \
		../../Programs/root/include/Vc/traits/is_index_sequence.h \
		../../Programs/root/include/Vc/common/indexsequence.h \
		../../Programs/root/include/Vc/traits/is_implicit_cast_allowed.h \
		../../Programs/root/include/Vc/traits/has_subscript_operator.h \
		../../Programs/root/include/Vc/traits/has_multiply_operator.h \
		../../Programs/root/include/Vc/traits/has_addition_operator.h \
		../../Programs/root/include/Vc/traits/has_equality_operator.h \
		../../Programs/root/include/Vc/traits/entry_type_of.h \
		../../Programs/root/include/Vc/common/permutation.h \
		../../Programs/root/include/Vc/scalar/mask.h \
		../../Programs/root/include/Vc/common/memoryfwd.h \
		../../Programs/root/include/Vc/common/vectorabi.h \
		../../Programs/root/include/Vc/common/simdarrayfwd.h \
		../../Programs/root/include/Vc/sse/types.h \
		../../Programs/root/include/Vc/avx/types.h \
		../../Programs/root/include/Vc/common/utility.h \
		../../Programs/root/include/Vc/scalar/detail.h \
		../../Programs/root/include/Vc/common/detail.h \
		../../Programs/root/include/Vc/common/generalinterface.h \
		../../Programs/root/include/Vc/common/loadinterface.h \
		../../Programs/root/include/Vc/common/storeinterface.h \
		../../Programs/root/include/Vc/common/gatherinterface.h \
		../../Programs/root/include/Vc/common/gatherinterface_deprecated.h \
		../../Programs/root/include/Vc/common/scatterinterface.h \
		../../Programs/root/include/Vc/common/scatterinterface_deprecated.h \
		../../Programs/root/include/Vc/scalar/vector.tcc \
		../../Programs/root/include/Vc/common/data.h \
		../../Programs/root/include/Vc/common/where.h \
		../../Programs/root/include/Vc/common/transpose.h \
		../../Programs/root/include/Vc/scalar/operators.h \
		../../Programs/root/include/Vc/scalar/simd_cast.h \
		../../Programs/root/include/Vc/common/simd_cast.h \
		../../Programs/root/include/Vc/scalar/type_traits.h \
		../../Programs/root/include/Vc/sse/vector.h \
		../../Programs/root/include/Vc/sse/intrinsics.h \
		../../Programs/root/include/Vc/common/storage.h \
		../../Programs/root/include/Vc/common/aliasingentryhelper.h \
		../../Programs/root/include/Vc/common/maskbool.h \
		../../Programs/root/include/Vc/avx/intrinsics.h \
		../../Programs/root/include/Vc/common/fix_clang_emmintrin.h \
		../../Programs/root/include/Vc/sse/const_data.h \
		../../Programs/root/include/Vc/sse/debug.h \
		../../Programs/root/include/Vc/sse/shuffle.h \
		../../Programs/root/include/Vc/sse/vectorhelper.h \
		../../Programs/root/include/Vc/common/loadstoreflags.h \
		../../Programs/root/include/Vc/sse/vectorhelper.tcc \
		../../Programs/root/include/Vc/common/writemaskedvector.h \
		../../Programs/root/include/Vc/avx/vector.h \
		../../Programs/root/include/Vc/avx/casts.h \
		../../Programs/root/include/Vc/sse/casts.h \
		../../Programs/root/include/Vc/common/operators.h \
		../../Programs/root/include/Vc/common/simdarray.h \
		../../Programs/root/include/Vc/common/simdarrayhelper.h \
		../../Programs/root/include/Vc/common/simdmaskarray.h \
		../../Programs/root/include/Vc/common/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/common/interleave.h \
		../../Programs/root/include/Vc/common/alignedbase.h \
		../../Programs/root/include/Vc/scalar/helperimpl.h \
		../../Programs/root/include/Vc/scalar/math.h \
		../../Programs/root/include/Vc/scalar/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/sse/helperimpl.h \
		../../Programs/root/include/Vc/sse/deinterleave.tcc \
		../../Programs/root/include/Vc/sse/prefetches.tcc \
		../../Programs/root/include/Vc/sse/math.h \
		../../Programs/root/include/Vc/sse/const.h \
		../../Programs/root/include/Vc/sse/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/avx/helperimpl.h \
		../../Programs/root/include/Vc/avx/math.h \
		../../Programs/root/include/Vc/avx/limits.h \
		../../Programs/root/include/Vc/avx/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/common/math.h \
		../../Programs/root/include/Vc/common/trigonometric.h \
		../../Programs/root/include/Vc/common/logarithm.h \
		../../Programs/root/include/Vc/common/exponential.h \
		../../Programs/root/include/Vc/common/vectortuple.h \
		../../Programs/root/include/Vc/common/iif.h \
		../../Programs/root/include/Vc/type_traits \
		../../Programs/root/include/Vc/IO \
		../../Programs/root/include/Vc/Memory \
		../../Programs/root/include/Vc/common/memory.h \
		../../Programs/root/include/Vc/common/memorybase.h \
		../../Programs/root/include/Vc/common/malloc.h \
		../../Programs/root/include/Vc/common/interleavedmemory.h \
		../../Programs/root/include/Vc/common/make_unique.h \
		../../Programs/root/include/Vc/Utils \
		../../Programs/root/include/Vc/common/deinterleave.h \
		../../Programs/root/include/Vc/common/makeContainer.h \
		../../Programs/root/include/Vc/Allocator \
		../../Programs/root/include/Vc/iterators \
		../../Programs/root/include/Vc/common/iterators.h \
		../../Programs/root/include/Vc/common/elementreference.h \
		../../Programs/root/include/Vc/simdize \
		../../Programs/root/include/Vc/common/simdize.h \
		../../Programs/root/include/Vc/span \
		../../Programs/root/include/Vc/common/span.h \
		../../Programs/root/include/VecCore/VecCore \
		../../Programs/root/include/VecCore/Version.h \
		../../Programs/root/include/VecCore/Assert.h \
		../../Programs/root/include/VecCore/Common.h \
		../../Programs/root/include/VecCore/CUDA.h \
		../../Programs/root/include/VecCore/SIMD.h \
		../../Programs/root/include/VecCore/Types.h \
		../../Programs/root/include/VecCore/Backend/Interface.h \
		../../Programs/root/include/VecCore/Backend/Implementation.h \
		../../Programs/root/include/VecCore/Limits.h \
		../../Programs/root/include/VecCore/Backend/Deprecated.h \
		../../Programs/root/include/VecCore/Backend/Scalar.h \
		../../Programs/root/include/VecCore/Backend/ScalarWrapper.h \
		../../Programs/root/include/VecCore/Backend/SIMDSizes.h \
		../../Programs/root/include/VecCore/Backend/Vc.h \
		../../Programs/root/include/VecCore/Backend/VcScalar.h \
		../../Programs/root/include/VecCore/Backend/VcVector.h \
		../../Programs/root/include/VecCore/Backend/VcSimdArray.h \
		../../Programs/root/include/VecCore/Backend/UMESimd.h \
		../../Programs/root/include/VecCore/Backend/UMESimdCommon.h \
		../../Programs/root/include/VecCore/Backend/UMESimdArray.h \
		../../Programs/root/include/VecCore/VecMath.h \
		../../Programs/root/include/VecCore/Utilities.h \
		../../Programs/root/include/TF1AbsComposition.h \
		../../Programs/root/include/TMath.h \
		../../Programs/root/include/TError.h \
		../../Programs/root/include/Math/ParamFunctor.h \
		../../Programs/root/include/TGraph.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_histogram.h \
		/usr/local/qwt-6.1.5/include/qwt_column_symbol.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_curve.h \
		/usr/local/qwt-6.1.5/include/qwt_picker_machine.h \
		ui_mainwindow.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_grid.h \
		/usr/local/qwt-6.1.5/include/qwt_symbol.h \
		/usr/local/qwt-6.1.5/include/qwt_legend.h \
		/usr/local/qwt-6.1.5/include/qwt_abstract_legend.h \
		/usr/local/qwt-6.1.5/include/qwt_scale_engine.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_renderer.h \
		mylabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mylabel.o: mylabel.cpp mylabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mylabel.o mylabel.cpp

spectrum.o: spectrum.cpp spectrum.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.5/include/qwt_global.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_item.h \
		/usr/local/qwt-6.1.5/include/qwt_text.h \
		/usr/local/qwt-6.1.5/include/qwt_legend_data.h \
		/usr/local/qwt-6.1.5/include/qwt_graphic.h \
		/usr/local/qwt-6.1.5/include/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.5/include/qwt_scale_div.h \
		/usr/local/qwt-6.1.5/include/qwt_interval.h \
		/usr/local/qwt-6.1.5/include/qwt_series_data.h \
		/usr/local/qwt-6.1.5/include/qwt_samples.h \
		/usr/local/qwt-6.1.5/include/qwt_point_3d.h \
		/usr/local/qwt-6.1.5/include/qwt_point_polar.h \
		/usr/local/qwt-6.1.5/include/qwt_math.h \
		/usr/local/qwt-6.1.5/include/qwt_series_store.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_picker.h \
		/usr/local/qwt-6.1.5/include/qwt_picker.h \
		/usr/local/qwt-6.1.5/include/qwt_event_pattern.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_marker.h \
		/usr/local/qwt-6.1.5/include/qwt_plot_canvas.h \
		../../Programs/root/include/TH1F.h \
		../../Programs/root/include/TH1.h \
		../../Programs/root/include/TAxis.h \
		../../Programs/root/include/TNamed.h \
		../../Programs/root/include/TObject.h \
		../../Programs/root/include/RConfigure.h \
		../../Programs/root/include/Rtypes.h \
		../../Programs/root/include/RtypesCore.h \
		../../Programs/root/include/ROOT/RConfig.hxx \
		../../Programs/root/include/RVersion.h \
		../../Programs/root/include/DllImport.h \
		../../Programs/root/include/snprintf.h \
		../../Programs/root/include/strlcpy.h \
		../../Programs/root/include/TGenericClassInfo.h \
		../../Programs/root/include/TSchemaHelper.h \
		../../Programs/root/include/TIsAProxy.h \
		../../Programs/root/include/TVirtualIsAProxy.h \
		../../Programs/root/include/TStorage.h \
		../../Programs/root/include/TVersionCheck.h \
		../../Programs/root/include/TString.h \
		../../Programs/root/include/TMathBase.h \
		../../Programs/root/include/ROOT/RStringView.hxx \
		../../Programs/root/include/ROOT/RWrap_libcpp_string_view.h \
		../../Programs/root/include/ROOT/libcpp_string_view.h \
		../../Programs/root/include/ROOT/TypeTraits.hxx \
		../../Programs/root/include/TAttAxis.h \
		../../Programs/root/include/TArrayD.h \
		../../Programs/root/include/TArray.h \
		../../Programs/root/include/TAttLine.h \
		../../Programs/root/include/TAttFill.h \
		../../Programs/root/include/TAttMarker.h \
		../../Programs/root/include/TArrayC.h \
		../../Programs/root/include/TArrayS.h \
		../../Programs/root/include/TArrayI.h \
		../../Programs/root/include/TArrayF.h \
		../../Programs/root/include/Foption.h \
		../../Programs/root/include/Fit/FitExecutionPolicy.h \
		../../Programs/root/include/TVectorFfwd.h \
		../../Programs/root/include/TVectorDfwd.h \
		../../Programs/root/include/TFitResultPtr.h \
		../../Programs/root/include/TF1.h \
		../../Programs/root/include/TFormula.h \
		../../Programs/root/include/TBits.h \
		../../Programs/root/include/TMethodCall.h \
		../../Programs/root/include/TDictionary.h \
		../../Programs/root/include/ESTLType.h \
		../../Programs/root/include/TInterpreter.h \
		../../Programs/root/include/TDataType.h \
		../../Programs/root/include/TInterpreterValue.h \
		../../Programs/root/include/TVirtualRWMutex.h \
		../../Programs/root/include/TVirtualMutex.h \
		../../Programs/root/include/Math/Types.h \
		../../Programs/root/include/Vc/Vc \
		../../Programs/root/include/Vc/vector.h \
		../../Programs/root/include/Vc/scalar/vector.h \
		../../Programs/root/include/Vc/scalar/types.h \
		../../Programs/root/include/Vc/common/types.h \
		../../Programs/root/include/Vc/global.h \
		../../Programs/root/include/Vc/fwddecl.h \
		../../Programs/root/include/Vc/version.h \
		../../Programs/root/include/Vc/traits/type_traits.h \
		../../Programs/root/include/Vc/traits/decay.h \
		../../Programs/root/include/Vc/traits/has_no_allocated_data.h \
		../../Programs/root/include/Vc/array \
		../../Programs/root/include/Vc/common/subscript.h \
		../../Programs/root/include/Vc/vector \
		../../Programs/root/include/Vc/scalar/macros.h \
		../../Programs/root/include/Vc/common/macros.h \
		../../Programs/root/include/Vc/traits/has_contiguous_storage.h \
		../../Programs/root/include/Vc/traits/is_functor_argument_immutable.h \
		../../Programs/root/include/Vc/traits/is_output_iterator.h \
		../../Programs/root/include/Vc/traits/is_index_sequence.h \
		../../Programs/root/include/Vc/common/indexsequence.h \
		../../Programs/root/include/Vc/traits/is_implicit_cast_allowed.h \
		../../Programs/root/include/Vc/traits/has_subscript_operator.h \
		../../Programs/root/include/Vc/traits/has_multiply_operator.h \
		../../Programs/root/include/Vc/traits/has_addition_operator.h \
		../../Programs/root/include/Vc/traits/has_equality_operator.h \
		../../Programs/root/include/Vc/traits/entry_type_of.h \
		../../Programs/root/include/Vc/common/permutation.h \
		../../Programs/root/include/Vc/scalar/mask.h \
		../../Programs/root/include/Vc/common/memoryfwd.h \
		../../Programs/root/include/Vc/common/vectorabi.h \
		../../Programs/root/include/Vc/common/simdarrayfwd.h \
		../../Programs/root/include/Vc/sse/types.h \
		../../Programs/root/include/Vc/avx/types.h \
		../../Programs/root/include/Vc/common/utility.h \
		../../Programs/root/include/Vc/scalar/detail.h \
		../../Programs/root/include/Vc/common/detail.h \
		../../Programs/root/include/Vc/common/generalinterface.h \
		../../Programs/root/include/Vc/common/loadinterface.h \
		../../Programs/root/include/Vc/common/storeinterface.h \
		../../Programs/root/include/Vc/common/gatherinterface.h \
		../../Programs/root/include/Vc/common/gatherinterface_deprecated.h \
		../../Programs/root/include/Vc/common/scatterinterface.h \
		../../Programs/root/include/Vc/common/scatterinterface_deprecated.h \
		../../Programs/root/include/Vc/scalar/vector.tcc \
		../../Programs/root/include/Vc/common/data.h \
		../../Programs/root/include/Vc/common/where.h \
		../../Programs/root/include/Vc/common/transpose.h \
		../../Programs/root/include/Vc/scalar/operators.h \
		../../Programs/root/include/Vc/scalar/simd_cast.h \
		../../Programs/root/include/Vc/common/simd_cast.h \
		../../Programs/root/include/Vc/scalar/type_traits.h \
		../../Programs/root/include/Vc/sse/vector.h \
		../../Programs/root/include/Vc/sse/intrinsics.h \
		../../Programs/root/include/Vc/common/storage.h \
		../../Programs/root/include/Vc/common/aliasingentryhelper.h \
		../../Programs/root/include/Vc/common/maskbool.h \
		../../Programs/root/include/Vc/avx/intrinsics.h \
		../../Programs/root/include/Vc/common/fix_clang_emmintrin.h \
		../../Programs/root/include/Vc/sse/const_data.h \
		../../Programs/root/include/Vc/sse/debug.h \
		../../Programs/root/include/Vc/sse/shuffle.h \
		../../Programs/root/include/Vc/sse/vectorhelper.h \
		../../Programs/root/include/Vc/common/loadstoreflags.h \
		../../Programs/root/include/Vc/sse/vectorhelper.tcc \
		../../Programs/root/include/Vc/common/writemaskedvector.h \
		../../Programs/root/include/Vc/avx/vector.h \
		../../Programs/root/include/Vc/avx/casts.h \
		../../Programs/root/include/Vc/sse/casts.h \
		../../Programs/root/include/Vc/common/operators.h \
		../../Programs/root/include/Vc/common/simdarray.h \
		../../Programs/root/include/Vc/common/simdarrayhelper.h \
		../../Programs/root/include/Vc/common/simdmaskarray.h \
		../../Programs/root/include/Vc/common/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/common/interleave.h \
		../../Programs/root/include/Vc/common/alignedbase.h \
		../../Programs/root/include/Vc/scalar/helperimpl.h \
		../../Programs/root/include/Vc/scalar/math.h \
		../../Programs/root/include/Vc/scalar/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/sse/helperimpl.h \
		../../Programs/root/include/Vc/sse/deinterleave.tcc \
		../../Programs/root/include/Vc/sse/prefetches.tcc \
		../../Programs/root/include/Vc/sse/math.h \
		../../Programs/root/include/Vc/sse/const.h \
		../../Programs/root/include/Vc/sse/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/avx/helperimpl.h \
		../../Programs/root/include/Vc/avx/math.h \
		../../Programs/root/include/Vc/avx/limits.h \
		../../Programs/root/include/Vc/avx/simd_cast_caller.tcc \
		../../Programs/root/include/Vc/common/math.h \
		../../Programs/root/include/Vc/common/trigonometric.h \
		../../Programs/root/include/Vc/common/logarithm.h \
		../../Programs/root/include/Vc/common/exponential.h \
		../../Programs/root/include/Vc/common/vectortuple.h \
		../../Programs/root/include/Vc/common/iif.h \
		../../Programs/root/include/Vc/type_traits \
		../../Programs/root/include/Vc/IO \
		../../Programs/root/include/Vc/Memory \
		../../Programs/root/include/Vc/common/memory.h \
		../../Programs/root/include/Vc/common/memorybase.h \
		../../Programs/root/include/Vc/common/malloc.h \
		../../Programs/root/include/Vc/common/interleavedmemory.h \
		../../Programs/root/include/Vc/common/make_unique.h \
		../../Programs/root/include/Vc/Utils \
		../../Programs/root/include/Vc/common/deinterleave.h \
		../../Programs/root/include/Vc/common/makeContainer.h \
		../../Programs/root/include/Vc/Allocator \
		../../Programs/root/include/Vc/iterators \
		../../Programs/root/include/Vc/common/iterators.h \
		../../Programs/root/include/Vc/common/elementreference.h \
		../../Programs/root/include/Vc/simdize \
		../../Programs/root/include/Vc/common/simdize.h \
		../../Programs/root/include/Vc/span \
		../../Programs/root/include/Vc/common/span.h \
		../../Programs/root/include/VecCore/VecCore \
		../../Programs/root/include/VecCore/Version.h \
		../../Programs/root/include/VecCore/Assert.h \
		../../Programs/root/include/VecCore/Common.h \
		../../Programs/root/include/VecCore/CUDA.h \
		../../Programs/root/include/VecCore/SIMD.h \
		../../Programs/root/include/VecCore/Types.h \
		../../Programs/root/include/VecCore/Backend/Interface.h \
		../../Programs/root/include/VecCore/Backend/Implementation.h \
		../../Programs/root/include/VecCore/Limits.h \
		../../Programs/root/include/VecCore/Backend/Deprecated.h \
		../../Programs/root/include/VecCore/Backend/Scalar.h \
		../../Programs/root/include/VecCore/Backend/ScalarWrapper.h \
		../../Programs/root/include/VecCore/Backend/SIMDSizes.h \
		../../Programs/root/include/VecCore/Backend/Vc.h \
		../../Programs/root/include/VecCore/Backend/VcScalar.h \
		../../Programs/root/include/VecCore/Backend/VcVector.h \
		../../Programs/root/include/VecCore/Backend/VcSimdArray.h \
		../../Programs/root/include/VecCore/Backend/UMESimd.h \
		../../Programs/root/include/VecCore/Backend/UMESimdCommon.h \
		../../Programs/root/include/VecCore/Backend/UMESimdArray.h \
		../../Programs/root/include/VecCore/VecMath.h \
		../../Programs/root/include/VecCore/Utilities.h \
		../../Programs/root/include/TF1AbsComposition.h \
		../../Programs/root/include/TMath.h \
		../../Programs/root/include/TError.h \
		../../Programs/root/include/Math/ParamFunctor.h \
		../../Programs/root/include/TGraph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spectrum.o spectrum.cpp

qrc_rhino_icon.o: qrc_rhino_icon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_rhino_icon.o qrc_rhino_icon.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_mylabel.o: moc_mylabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mylabel.o moc_mylabel.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

